### ISSUE TITLE
Code is outdated

### ISSUE THREAD

**Issue by nvinayvarma189** [deeplearning4j/tf-import#1]
Hey. I have tried out this code and it seems to have a lot of errors. Here are some I have come across:
1. `.get()` from `import org.nd4j.linalg.factory.Nd4j;` does not exist.
2. Exceptions are not handled on the methods. 
3. The datatype should be `int` on this [line](https://github.com/deeplearning4j/tf-import/blob/master/mnist/Mnist.java#L62)
4. should be `private static SameDiff` on this [line](https://github.com/deeplearning4j/tf-import/blob/master/mnist/Mnist.java#L13)
5. i=0 maybe. On this [line](https://github.com/deeplearning4j/tf-import/blob/master/mnist/Mnist.java#L40)
6. Paramter should be changed to `filepath` on this [line](https://github.com/deeplearning4j/tf-import/blob/master/mnist/Mnist.java#L36)

Could you please update these?

**Comment by AlexDBlack** [comment]
This repository is not being maintained.
There are a few tensorflow import graphs in the main examples repository here:
https://github.com/deeplearning4j/dl4j-examples/tree/master/tf-import-examples/src/main/java/org/nd4j/examples
